# Runs validate_reactions.py on all new and changed files in this PR.

name: Submission

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ord-submissions
      uses: actions/checkout@v2
    - name: Checkout ord-schema
        uses: actions/checkout@v2
        with:
          repository: Open-Reaction-Database/ord-schema
          path: ord-schema
    - name: Identify changed files
      # NOTE(kearnes): This sets the NUM_CHANGED_FILES variable.
      run: |
        cd "${GITHUB_WORKSPACE}"
        ./ord-schema/actions/changed_files.sh
    - name: Install miniconda
      uses: goanpeca/setup-miniconda@v1.0.2
      with:
        python-version: '3.7'
        auto-update-conda: true
      if: env.NUM_CHANGED_FILES != '0'
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        cd "${GITHUB_WORKSPACE}/ord-schema"
        conda install --file requirements.txt
        conda install -c rdkit rdkit
        python setup.py install
      if: env.NUM_CHANGED_FILES != '0'
    - name: Validate submission
      shell: bash -l {0}
      run: |
        cd "${GITHUB_WORKSPACE}"
        python ./ord-schema/ord_schema/process_dataset.py \
          --input_file=changed_pbtxt_files.txt \
          --input_format=pbtxt \
          --update \
          --cleanup
      if: env.NUM_CHANGED_FILES != '0'
    - name: Commit updates
      run: |
        cd "${GITHUB_WORKSPACE}"
        ./ord-schema/actions/commit_changes.sh "Validate/update submission"
      if: env.NUM_CHANGED_FILES != '0'
